### ISSUE TITLE
Server issue

### ISSUE THREAD

**Issue by cavis** [PRX/play.prx.org#204]
Seen: ECS task died for some reason.

```
Parse Error
_http_server.js:221
throw new errors.Error('ERR_HTTP_HEADERS_SENT', 'render');
^
Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client
at ServerResponse.writeHead (_http_server.js:221:13)
at ServerResponse.writeHead (/app/node_modules/on-headers/index.js:55:19)
at ClientRequest.requester.request.on (/app/lib/server.js:41:9)
at ClientRequest.emit (events.js:159:13)
at Socket.socketOnData (_http_client.js:445:9)
at Socket.emit (events.js:159:13)
at addChunk (_stream_readable.js:265:12)
at readableAddChunk (_stream_readable.js:252:11)
at Socket.Readable.push (_stream_readable.js:209:10)
at TCP.onread (net.js:608:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! play.prx.org@0.2.0 serve: `node lib/server.js dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the play.prx.org@0.2.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /app/.npm/_logs/2019-02-12T16_39_00_838Z-debug.log
```

**Comment by cavis** [comment]
Have also seen this in the logs, with Play returning 500s:

```
connect EADDRNOTAVAIL 2607:f8b0:4004:810::2013:80 - Local (:::0)
```

**Comment by cavis** [comment]
Also seeing some issues where we fail to proxy the feed (or we're proxying a 5XX error):

```
getaddrinfo EAI_AGAIN feeds.thisiscriminal.com:80
```
